jar: classes
	jar cfm jquest.jar manifest.mf -C build/classes .

classes: dir
	javac -Xlint:all -sourcepath javaquest/ -d build/classes javaquest/*.java

dir:
	if [ ! -d build/classes ]; then mkdir -p build/classes; fi
	if [ ! -d build/jar ]; then mkdir -p build/jar; fi

clean:
	if [ -d build ]; then rm build -R; fi
	if [ jquest.jar ]; then rm jquest.jar -R; fi

run:
	java -jar jquest.jar
